name: animal
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - datasets==4.4.1
      - dill==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.121.3
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==12.0.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.14.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/user/miniconda3/envs/animal
